### PR TITLE
Clarification on RX group.

### PR DESCRIPTION
**Pull request by JaydenDownes**
Peach Host - WHMCS was never run under no license. This was an issue with a load balancer which resulted in Peach host having to contact WHMCS in regards to getting rid of IP restrictions which took some time. It would have helped if this was said in advance. As for downtime, from users experiences this as well as support is decently bad. 
As for RX Group, Etheral Solution, and FastSrv, I have been staff there in the past and been a member and buyer for many months and I see no issues nor complaints from anyone. If you want evidence to back any of this up head over to their discords. 
If this summer hosts idea is going to continue, it has to be done right and that means it has to be based off evidence and not just assumptions or saying things.

### CODE REVIEW

**Comment by rouing** [comment]
From ES Discord:

image
****

Peachy Host has proven themselves bad AND they have lost their DB apparently as no one can login to their accounts.

FastSrv is ran by someone very immature and has proven so in Host Chat

RXGroups management has attempted to strong arm Legendary Hosts over Summerhost (They have no attachment to it except me) and use the threats of Negative Reputation. After it was all said and done, they back pedaled on MC-Market 

https://www.mc-market.org/threads/343854/page-5#post-3071275

RX Group is to be avoided and NEVER will be removed.

**Comment by PaziHD** [comment]
Peach Hosting's database was never lost, we just updated some WHMCS things.
I was asleep when he sent those messages, and we had notified him to open a whmcs ticket.
Charlie has been fired for inactivity as of recently.

**Comment by PaziHD** [comment]
As for RX Group and FastSRV, they can and will defend themselves against (possibly false) claims about them.

**Comment by rouing** [comment]
Is that a threat?

**Pull request closed without merging**
