### PR TITLE
remove iwa-hosting website updated

### PR DESCRIPTION
**Pull request by nigel12341**
i updated the website so the claims u make are now false.
i have never ever been owner of bombhost, they do host there whmcs with my webhosting thats it.

### CODE REVIEW

**Comment by rouing** [comment]
OH, well excuse me. Ill update the reason to include that your website was down for a ton of time and that you send emails to random people because you are salty.

**Comment by rouing** [comment]
You will never be removed. Any further attempts as PR's for removal of your own host will result in a block.

**Comment by rouing** [comment]
You will be blocked in 24 hours for making another request on GitLab after a warning.

**Comment by nigel12341** [comment]
Oh we start lieing about hosts on the webiste now? Sure.

**Comment by rouing** [comment]
It was true when the claim was made. Ill make updates in 4 mins

**Comment by nigel12341** [comment]
Ok update it. Remove that i dont use a theme and that i use announcement page as honepage pleas.

**Comment by rouing** [comment]
Can you even use english?

**Comment by nigel12341** [comment]
Yes. But i dont put much effort in it here because you dont listen anyway.

**Comment by rouing** [comment]
Oh look! He used a spellchecker this time around!

**Comment by rouing** [comment]
image

**Comment by nigel12341** [comment]
Are you going to be professional or nah?

**Comment by rouing** [comment]
Nope. No need to on this meme.

**Comment by nigel12341** [comment]
Summerhost is a joke anyways. Can't bekice anyone actually belives it. It would be good if you didn't lie about everything

**Comment by rouing** [comment]
image
Looks Salty
Looks like Spam
It's in my email.
Looks like an attempt to Intimidate the fact you Doxxed my Email.
Extremely Unprofessional
Your site is default everything on that theme.
Prices are meh....

**Pull request closed without merging**
